"""Subclass of fMainEditor, which is generated by wxFormBuilder."""

import wx
import Editors
from GlowEditorfShaderEditor import GlowEditorfShaderEditor

# Implementing fMainEditor
class GlowEditorfMainEditor( Editors.fMainEditor ):
	def __init__( self, parent ):
		Editors.fMainEditor.__init__( self, parent )
	
	# Handlers for fMainEditor events.
	def OnLoadDemoClick( self, event ):
		# TODO: Implement OnLoadDemoClick
		pass
	
	def OnSaveDemoClick( self, event ):
		# TODO: Implement OnSaveDemoClick
		pass
	
	def OnSkyboxDirChanged( self, event ):
		# TODO: Implement OnSkyboxDirChanged
		pass
	
	def OnSceneSelectionChoice( self, event ):
		# TODO: Implement OnSceneSelectionChoice
		pass
	
	def OnSceneGraphTreeRightDown( self, event ):
		# TODO: Implement OnSceneGraphTreeRightDown
		pass
	
	def OnCurveEditorLeftDown( self, event ):
		# TODO: Implement OnCurveEditorLeftDown
		pass
	
	def OnScrollZoomCurvesX( self, event ):
		# TODO: Implement OnScrollZoomCurvesX
		pass
	
	def OnScrollZoomCurvesY( self, event ):
		# TODO: Implement OnScrollZoomCurvesY
		pass
	
	def OnNewCurveClick( self, event ):
		# TODO: Implement OnNewCurveClick
		pass
	
	def OnLoadCurveClick( self, event ):
		# TODO: Implement OnLoadCurveClick
		pass
	
	def OnSaveCurveClick( self, event ):
		# TODO: Implement OnSaveCurveClick
		pass
	
	def OnLoadTextureClick( self, event ):
		# TODO: Implement OnLoadTextureClick
		pass
	
	def OnFirstTextureClick( self, event ):
		# TODO: Implement OnFirstTextureClick
		pass
	
	def OnUpTextureClick( self, event ):
		# TODO: Implement OnUpTextureClick
		pass
	
	def OnDownTextureClick( self, event ):
		# TODO: Implement OnDownTextureClick
		pass
	
	def OnLastTextureClick( self, event ):
		# TODO: Implement OnLastTextureClick
		pass
	
	def OnDeleteTextureClick( self, event ):
		# TODO: Implement OnDeleteTextureClick
		pass
	
	def OnLoadModelClick( self, event ):
		# TODO: Implement OnLoadModelClick
		pass
	
	def OnDeleteModelClick( self, event ):
		# TODO: Implement OnDeleteModelClick
		pass
	
	def OnMenuLoadRessources( self, event ):
		# TODO: Implement OnMenuLoadRessources
		pass
	
	def onMenuPhongEditor( self, event ):
		# TODO: Implement onMenuPhongEditor
		pass
	
	def OnMenuShaderEditor( self, event ):
		#f = GlowEditorfShaderEditor(None)
		#f.Show()

		GlowEditorfShaderEditor(None).Show()
		pass
	
	
