#ifndef __GlowEditorfPhongEditor__
#define __GlowEditorfPhongEditor__

/**
@file
Subclass of fPhongEditor, which is generated by wxFormBuilder.
*/

#include "Editors.h"

/** Implementing fPhongEditor */
class GlowEditorfPhongEditor : public fPhongEditor
{
protected:
	// Handlers for fPhongEditor events.
	void OnIdle( wxIdleEvent& event );
	void OnScrollAmbient( wxScrollEvent& event );
	void OnAmbientColorChanged( wxColourPickerEvent& event );
	void OnScrollDiffuse( wxScrollEvent& event );
	void OnDiffuseColorChanged( wxColourPickerEvent& event );
	void OnScrollSpecular( wxScrollEvent& event );
	void OnSpecularColorChanged( wxColourPickerEvent& event );
	
public:
	/** Constructor */
	GlowEditorfPhongEditor( wxWindow* parent );
};

#endif // __GlowEditorfPhongEditor__
