#ifndef __GlowEditorfPostProcessEditor__
#define __GlowEditorfPostProcessEditor__

/**
@file
Subclass of fPostProcessEditor, which is generated by wxFormBuilder.
*/

#include "Editors.h"

/** Implementing fPostProcessEditor */
class GlowEditorfPostProcessEditor : public fPostProcessEditor
{
protected:
	// Handlers for fPostProcessEditor events.
	void onBrightnessChange( wxScrollEvent& event );
	void onSaturationChange( wxScrollEvent& event );
	
public:
	/** Constructor */
	GlowEditorfPostProcessEditor( wxWindow* parent );
};

#endif // __GlowEditorfPostProcessEditor__
