"""Subclass of fPostProcessEditor, which is generated by wxFormBuilder."""

import wx
import Editors

# Implementing fPostProcessEditor
class GlowEditorfPostProcessEditor( Editors.fPostProcessEditor ):
	def __init__( self, parent ):
		Editors.fPostProcessEditor.__init__( self, parent )
	
	# Handlers for fPostProcessEditor events.
	def onBrightnessChange( self, event ):
		# TODO: Implement onBrightnessChange
		pass
	
	def onSaturationChange( self, event ):
		# TODO: Implement onSaturationChange
		pass
	
	
