"""Subclass of fPhongEditor, which is generated by wxFormBuilder."""

import wx
import Editors

# Implementing fPhongEditor
class GlowEditorfPhongEditor( Editors.fPhongEditor ):
	def __init__( self, parent ):
		Editors.fPhongEditor.__init__( self, parent )
	
	# Handlers for fPhongEditor events.
	def OnIdle( self, event ):
		# TODO: Implement OnIdle
		pass
	
	def OnScrollAmbient( self, event ):
		# TODO: Implement OnScrollAmbient
		pass
	
	def OnAmbientColorChanged( self, event ):
		# TODO: Implement OnAmbientColorChanged
		pass
	
	def OnScrollDiffuse( self, event ):
		# TODO: Implement OnScrollDiffuse
		pass
	
	def OnDiffuseColorChanged( self, event ):
		# TODO: Implement OnDiffuseColorChanged
		pass
	
	def OnScrollSpecular( self, event ):
		# TODO: Implement OnScrollSpecular
		pass
	
	def OnSpecularColorChanged( self, event ):
		# TODO: Implement OnSpecularColorChanged
		pass
	
	
