"""Subclass of fShaderEditor, which is generated by wxFormBuilder."""

import wx
import Editors

# Implementing fShaderEditor
class GlowEditorfShaderEditor( Editors.fShaderEditor ):
	def __init__( self, parent ):
		Editors.fShaderEditor.__init__( self, parent )
	
	# Handlers for fShaderEditor events.
	def OnChoiceShader( self, event ):
		# TODO: Implement OnChoiceShader
		pass
	
	def OnVertexFileChanged( self, event ):
		# TODO: Implement OnVertexFileChanged
		pass
	
	def OnButtonVertexLoad( self, event ):
		# TODO: Implement OnButtonVertexLoad
		pass
	
	def OnButtonVertexSave( self, event ):
		# TODO: Implement OnButtonVertexSave
		pass
	
	def OnTessellationControlFileChanged( self, event ):
		# TODO: Implement OnTessellationControlFileChanged
		pass
	
	def OnButtonTessellationLoad( self, event ):
		# TODO: Implement OnButtonTessellationLoad
		pass
	
	def OnButtonTessellationControlLoad( self, event ):
		# TODO: Implement OnButtonTessellationControlLoad
		pass
	
	def OnTessellationEvaluationFileChanged( self, event ):
		# TODO: Implement OnTessellationEvaluationFileChanged
		pass
	
	def OnButtonTessellationEvaluationLoad( self, event ):
		# TODO: Implement OnButtonTessellationEvaluationLoad
		pass
	
	def OnButtonTessellationEvaluationSave( self, event ):
		# TODO: Implement OnButtonTessellationEvaluationSave
		pass
	
	def OnGeometryFileChanged( self, event ):
		# TODO: Implement OnGeometryFileChanged
		pass
	
	def OnButtonGeometryLoad( self, event ):
		# TODO: Implement OnButtonGeometryLoad
		pass
	
	def OnFragmentFileChanged( self, event ):
		# TODO: Implement OnFragmentFileChanged
		pass
	
	def OnButtonFragmentLoad( self, event ):
		# TODO: Implement OnButtonFragmentLoad
		pass
	
	def OnLogLeftDClick( self, event ):
		# TODO: Implement OnLogLeftDClick
		pass
	
	def OnCompileClick( self, event ):
		# TODO: Implement OnCompileClick
		pass
	
	
