#ifndef __GlowEditorfMainEditor__
#define __GlowEditorfMainEditor__

/**
@file
Subclass of fMainEditor, which is generated by wxFormBuilder.
*/

#include "Editors.h"
#include "wx/filedlg.h"
#include "../System/Texture.h"
#include <vector>
#include "../System/CTMModel.h"
#include "GlowEditorfPhongEditor.h"
#include "GlowEditorfShaderEditor.h"
#include "GlowEditorfPostProcessEditor.h"
#include "../System/Skybox.h"
#include "../System/Engine.h"

/** Implementing fMainEditor */

//class Engine; //foward declaration
class GlowEditorfMainEditor : public fMainEditor
{
private:
	//fMainWindow
	std::vector<Texture*> textures;
	std::vector<Mesh*> models;
	Engine* engine;



protected:
	// Handlers for fMainEditor events.
	void OnMenuLoadRessources( wxCommandEvent& event );
	void onMenuPhongEditor( wxCommandEvent& event );
	void OnMenuShaderEditor( wxCommandEvent& event );
	void OnLoadTextureClick(wxCommandEvent& event );
	void OnLoadModelClick(wxCommandEvent& event );
	void OnDeleteModelClick(wxCommandEvent& event);
	void OnScrollZoomCurvesX( wxScrollEvent& event );
	void OnScrollZoomCurvesY( wxScrollEvent& event );
	void OnSkyboxDirChanged ( wxFileDirPickerEvent& event );
	void OnLoadDemoClick(wxCommandEvent& event );
	void OnSaveDemoClick(wxCommandEvent& event );
	void OnSceneGraphTreeRightDown(wxCommandEvent& event);
	void OnSceneSelectionChoice(wxCommandEvent& event);
	
public:
	Skybox* skybox;
	GlowEditorfMainEditor( wxWindow* parent );
    std::vector<Texture*> getTextures() const;
    void setTextures(std::vector<Texture*> textures);
    std::vector<Mesh*> getModels() const;
    void setModels(std::vector<Mesh*> models);
    GlowEditorfPhongEditor *getPhongEditor() const;
    GlowEditorfPostProcessEditor *getPostProcessEditor() const;
    GlowEditorfShaderEditor *getShaderEditor() const;
    GlowEditorfPhongEditor* fPhongEditor;
	GlowEditorfShaderEditor* fShaderEditor;
	GlowEditorfPostProcessEditor* fPostProcessEditor;

};

#endif // __GlowEditorfMainEditor__
